### PR TITLE
Support log level per plugin

### PR DESCRIPTION
**Pull request by okkez**
See also: http://docs.fluentd.org/v0.12/articles/logging#per-plugin-log

### CODE REVIEW

**Comment by roiravhon** [comment]
Hey, @okkez and thanks for that!
Read a bit, and I'm afraid to break compatibility with older fluentd versions.

Found this article - http://repeatedly.github.io/2014/02/new-log-level-parameter/

Can you please add to your PR this section?
```ruby
unless method_defined?(:log)
      define_method(:log) { $log }
end
```

**Comment by okkez** [comment]
I think we don't need to add compatibility method.
Because Fluentd v0.12.0 or later has `log` method.
And this plugin supports only Fluentd v0.12.0 or later. Not support Fluentd v0.10.x (v0.10.x has already reached  EOL).

https://github.com/logzio/fluent-plugin-logzio/blob/master/fluent-plugin-logzio.gemspec#L23

```ruby
s.add_dependency 'fluentd', '~> 0.12'
```

**Comment by roiravhon** [comment]
Good point you have there 😄 
I'll merge and upload to rubygems soon

**Comment by roiravhon** [comment]
Thanks @okkez, pushed to rubygems!

**Comment by roiravhon** [comment]
version 0.0.10

**Pull request merged**
