### PR TITLE
Add tags and timestamp in unbuffered plugin as well

### PR DESCRIPTION
**Pull request by IvanVergiliev**

### CODE REVIEW

**Comment by roiravhon** [comment]
@IvanVergiliev I want to decline this one since I really don't want anyone to use this plugin.
Fine by you?

**Comment by IvanVergiliev** [comment]
That works for me if you delete the plugin. Otherwise it's kind of confusing that it exists but has randomly limited functionality 🙂

**Comment by roiravhon** [comment]
I get your point.
I would love to delete it, but I can't break compatibility for people using it currently.

Merging, thanks

**Comment by roiravhon** [comment]
Pushed 0.0.12 to rubygems.
Thanks!

**Pull request merged**
